version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: anonymizer_db
      POSTGRES_USER: anonymizer_user
      POSTGRES_PASSWORD: anonymizer_pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "anonymizer_user"]
      interval: 10s
      retries: 5
      start_period: 20s

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: anonymizer_user
      RABBITMQ_DEFAULT_PASS: anonymizer_pass
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      retries: 5
      start_period: 20s

  redis:
    image: redis:6
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
      start_period: 20s

  backend:
    build:
      context: ./data-anonymizer-api
    image: data-anonymizer-backend  # Nome explícito para a imagem
    restart: always
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - ./data-anonymizer-api/.env
    volumes:
      - ./data-anonymizer-api:/app
    ports:
      - "8000:8000"

  celery:
    restart: always
    depends_on:
      backend:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    image: data-anonymizer-backend  # Agora usa a imagem correta
    command: celery -A core worker --loglevel=info
    env_file:
      - ./data-anonymizer-api/.env
    volumes:
      - ./data-anonymizer-api:/app

  celery-beat:
    restart: always
    depends_on:
      backend:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    image: data-anonymizer-backend  # Agora usa a imagem correta
    command: celery -A core beat --loglevel=info
    env_file:
      - ./data-anonymizer-api/.env
    volumes:
      - ./data-anonymizer-api:/app

  frontend:
    build:
      context: ./data-anonymizer-ui
    image: data-anonymizer-frontend
    restart: always
    depends_on:
      - backend
    env_file:
      - ./data-anonymizer-ui/.env
    ports:
      - "3000:3000"
    volumes:
      - ./data-anonymizer-ui:/app

volumes:
  pgdata:
